version: 2.1
jobs:
  build:
  
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "78:b4:21:9e:e3:15:51:cc:44:a2:36:50:ab:6d:7f:95"
      - run:
          name: "add creatr to known host"
          command: ssh-keyscan -H 3.137.125.234 >> ~/.ssh/known_hosts
      - run:
         name: "copy artifects" 
         command: rsync -azp --exclude .git /home/circleci/project/ ubuntu@3.137.125.234:/data/www/advizuru.web/public/newhtml/